src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message implements EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modifyAt;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enable;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getModifyAt(): ?\DateTimeInterface
    {
        return $this->modifyAt;
    }

    public function setModifyAt(?\DateTimeInterface $modifyAt): self
    {
        $this->modifyAt = $modifyAt;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    private $username;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $emailValidated;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $emailValidatedToken;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $forget_token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $loginAt;

    /**
     * @var ?string
     */
    private $plainPassword;

    /**
     * @var ?string
     */
    private $plainPasswordConfirmation;
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modifiedAt;


    /**
     * @ORM\Column(type="boolean")
     */
    private $enable;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Organisme", mappedBy="users")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private $organismes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Corbeille", mappedBy="users")
     * @ORM\OrderBy({"name" = "ASC"})
     */
    private $corbeilles;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove"})
     */
    private $Avatar;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\IndicatorValueHistory", mappedBy="user")
     */
    private $indicatorValueHistories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActionState", mappedBy="user")
     */
    private $actionStates;

    public function __construct()
    {
        $this->organismes = new ArrayCollection();
        $this->corbeilles = new ArrayCollection();
        $this->indicatorValueHistories = new ArrayCollection();
        $this->actionStates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPasswordConfirmation(string $plainPasswordConfirmation): self
    {
        $this->plainPasswordConfirmation = $plainPasswordConfirmation;

        return $this;
    }

    public function getPlainPasswordConfirmation(): ?string
    {
        return $this->plainPasswordConfirmation;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmailValidated(): ?bool
    {
        return $this->emailValidated;
    }

    public function setEmailValidated(bool $emailValidated): self
    {
        $this->emailValidated = $emailValidated;

        return $this;
    }

    public function getEmailValidatedToken(): ?string
    {
        return $this->emailValidatedToken;
    }

    public function setEmailValidatedToken(?string $emailValidatedToken): self
    {
        $this->emailValidatedToken = $emailValidatedToken;

        return $this;
    }

    public function getLoginAt(): ?\DateTimeInterface
    {
        return $this->loginAt;
    }

    public function setLoginAt(?\DateTimeInterface $loginAt): self
    {
        $this->loginAt = $loginAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(?\DateTimeInterface $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    public function getForgetToken(): ?string
    {
        return $this->forget_token;
    }

    public function setForgetToken(?string $forget_token): self
    {
        $this->forget_token = $forget_token;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Organisme[]
     */
    public function getOrganismes(): Collection
    {
        return $this->organismes;
    }

    public function addOrganisme(Organisme $organisme): self
    {
        if (!$this->organismes->contains($organisme)) {
            $this->organismes[] = $organisme;
            $organisme->addUser($this);
        }

        return $this;
    }

    public function removeOrganisme(Organisme $organisme): self
    {
        if ($this->organismes->contains($organisme)) {
            $this->organismes->removeElement($organisme);
            $organisme->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Corbeille[]
     */
    public function getCorbeilles(): Collection
    {
        return $this->corbeilles;
    }

    public function addCorbeille(Corbeille $corbeille): self
    {
        if (!$this->corbeilles->contains($corbeille)) {
            $this->corbeilles[] = $corbeille;
            $corbeille->addUser($this);
        }

        return $this;
    }

    public function removeCorbeille(Corbeille $corbeille): self
    {
        if ($this->corbeilles->contains($corbeille)) {
            $this->corbeilles->removeElement($corbeille);
            $corbeille->removeUser($this);
        }

        return $this;
    }

    public function getAvatar(): ?Avatar
    {
        return $this->Avatar;
    }

    public function setAvatar(?Avatar $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    /**
     * @return Collection|IndicatorValueHistory[]
     */
    public function getIndicatorValueHistories(): Collection
    {
        return $this->indicatorValueHistories;
    }

    public function addIndicatorValueHistory(IndicatorValueHistory $indicatorValueHistory): self
    {
        if (!$this->indicatorValueHistories->contains($indicatorValueHistory)) {
            $this->indicatorValueHistories[] = $indicatorValueHistory;
            $indicatorValueHistory->setUser($this);
        }

        return $this;
    }

    public function removeIndicatorValueHistory(IndicatorValueHistory $indicatorValueHistory): self
    {
        if ($this->indicatorValueHistories->contains($indicatorValueHistory)) {
            $this->indicatorValueHistories->removeElement($indicatorValueHistory);
            // set the owning side to null (unless already changed)
            if ($indicatorValueHistory->getUser() === $this) {
                $indicatorValueHistory->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ActionState[]
     */
    public function getActionStates(): Collection
    {
        return $this->actionStates;
    }

    public function addActionState(ActionState $actionState): self
    {
        if (!$this->actionStates->contains($actionState)) {
            $this->actionStates[] = $actionState;
            $actionState->setUser($this);
        }

        return $this;
    }

src/Form/Admin/MessageType.php
<?php

namespace App\Form\Admin;

use App\Entity\Message;
use App\Form\AppTypeAbstract;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AppTypeAbstract
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',ChoiceType::class,
                ['choices' => [
                    'Administration' => 'admin',
                    'Documentation' => 'doc',
                    'Page d\'accueil'=>'home',
                    'Tableau de bord' => 'dashboard',

                ]])
            ->add('enable', CheckboxType::class,
                [
                    self::LABEL => ' ',
                    self::REQUIRED => false,
                ])
            ->add('content', TextareaType::class, [
                self::LABEL => 'Description',
                self::REQUIRED => false,
                self::ATTR => [self::ROWS => 3, self::CSS_CLASS => 'textarea'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/Admin/MessageController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Message;
use App\Form\Admin\MessageType;
use App\Manager\MessageManager;
use App\Repository\MessageRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/message")
 */
class MessageController extends AbstractController
{
    /**
     * @Route("/", name="message_index", methods={"GET"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function index(MessageRepository $messageRepository): Response
    {
        return $this->render('message/index.html.twig', [
            'messages' => $messageRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="message_new", methods={"GET","POST"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function new(Request $request, MessageManager $manager): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message
                ->setUser($this->getUser());
            $manager->save($message);

            return $this->redirectToRoute('message_edit',['id'=>$message->getId()]);
        }

        return $this->render('message/new.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="message_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function edit(Request $request, Message $message, MessageManager $messageManager): Response
    {
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message
                ->setUser($this->getUser())
                ;
            $messageManager->save($message);

            return $this->redirectToRoute('message_edit',['id'=>$message->getId()]);
        }

        return $this->render('message/edit.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="message_delete", methods={"DELETE"})
     * @IsGranted("ROLE_GESTIONNAIRE")
     */
    public function delete(Request $request, Message $message, MessageManager $messageManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $messageManager->remove($message);
        }

        return $this->redirectToRoute('message_index');
    }
}

templates/message/_show_messages.html.twig
<!--
/* VERSION 1.0.0 */
/* EMMANUEL SAUVAGE */
-->
{% if messages|length > 0 %}
    <div class="card">
        <div class="card-body">
            <div class="direct-chat-messages">
                {% for message in messages %}
                {% if message and message.content and message.enable %}
                <div class="direct-chat-msg showOver"  id="message_{{ message.id }}">
                    <div class="direct-chat-infos clearfix">
                        <span class="direct-chat-name float-left">{{ message.user.name }}</span>

                        <span class="direct-chat-timestamp float-right">{{ message.modifyat | date('d/m/Y H:i:s') }}</span>

                        {% if is_granted('ROLE_GESTIONNAIRE') %}
                            <div class=" float-right text-xs hide mr-5" id="message_{{ message.id }}_span">
                                <a href="{{ path('message_edit',{id:message.id}) }}" class="text-indigo">
                                    <i class="fa fa-cog"></i> modifier
                                </a>
                            </div>
                        {% endif %}


                    </div>
                    <img class="direct-chat-img" src="{{ message.user.avatar.image }}" alt="message user image">
                    <div class="direct-chat-text">
                        {{ message.content | raw }}
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}

{% set title='Messages' %}
{% set route_index='message_index' %}
{% set entityName='message' %}
{% set entity = message %}

{% block title %}{{ parent() }} {{ title }}{% endblock %}

{% block stylesheets %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ absolute_url( asset('plugins/select2/css/select2.min.css')) }}">
    <link rel="stylesheet"
          href="{{ absolute_url( asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ absolute_url( asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')) }}">
{% endblock %}

{% block body_header %}
    {{ include('admin/_body_header.html.twig', {domaine: title , id : entity.id, index : route_index}) }}
{% endblock %}

{% block sidebar_sommaire %}

{% endblock %}

{% block sidebar_button %}
    {% if is_granted('ROLE_GESTIONNAIRE') %}
        {{ include('share/__btn_save_onclick.html.twig') }}
        <span class="mb-3"></span>
        <span class="btn btn-danger " onclick="$('#delete').click();">
            <i class="fas fa-trash"></i> Supprimer
        </span>
    {% endif %}
    <span class="mb-3"></span>
    {{ include('share/__btn_return_list.html.twig',
        {   url:route_index
        }) }}
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-6  ">
            <div class="card ">
                <div class="card-body">
                    <div class="form-group row">
                        {{ form_label(form.name,'', { 'label_attr': {'class':'col-sm-3 col-form-label' }}) }}
                        <div class="col">
                            {{ form_errors(form.name) }}
                            {{ form_widget(form.name) }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="{{ form.enable.vars.id }}">
                            Afficher
                        </label>
                        <div class="col mt-1">
                            {{ form_row(form.enable) }}
                        </div>
                    </div>
                    {{ form_row(form.content) }}
                </div>
            </div>
        </div>
    </div>
    <div class="d-none">
        {{ include('share/__btn_save.html.twig') }}
        {{ form_rest(form) }}
    </div>
    {{ form_end(form) }}
    <div class="d-none">
        {{ include('share/_delete_form.html.twig',{domaine: entityName,id:entity.id}) }}
    </div>
{% endblock %}


{% block javascripts %}
    <script src="{{ absolute_url( asset('plugins/select2/js/select2.full.min.js')) }}"></script>
    <script src="{{ absolute_url( asset('js/add_sidebar.js')) }}"></script>
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} Message {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ absolute_url( asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css')) }}">
    <link rel="stylesheet"
          href="{{ absolute_url( asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')) }}">
{% endblock %}

{% block body_header %}
    {{ include('admin/_body_header.html.twig', {'domaine': 'Message' }) }}
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <table id="tableAdministration" class="table table-striped " style="width:100%">
                        <thead>
                        <tr>
                            <th class="all">#</th>
                            <th class="all">Page</th>
                            <th class="all ">Message</th>
                            <th class="desktop ">Utilisateur</th>
                            <th class="all text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for message in messages %}
                            <tr>
                                <td>{{ message.id }}</td>
                                <td>
                                        <span class="text-{{ message.enable ? 'gray-dark' : 'danger text-bold' }}">
                                            {{ message.name }}
                                        </span>
                                </td>
                                <td >{{ message.content | raw }}</td>
                                <td>
                                    {{ message.user.name }}
                                </td>
                                <td class="d-flex justify-content-center align-items-center">
                                    {% if is_granted('ROLE_GESTIONNAIRE') %}
                                        <a class="btn btn-info btn-sm"
                                           href="{{ path('message_edit', {'id': message.id}) }}">
                                            <i class="fas fa-pencil-alt"></i> Modifier
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="5">Aucun d'enregistrement</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        {% if is_granted('ROLE_GESTIONNAIRE') %}
            <div class="card-header">
                <a class="btn btn-success" href="{{ path('message_new') }}">
                    <i class="fas fa-plus"></i> Ajouter un élément
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}


{% block javascripts %}
    <script src="{{ absolute_url( asset('plugins/datatables/jquery.dataTables.js')) }}"></script>
    <script src="{{ absolute_url( asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')) }}"></script>
    <script src="{{ absolute_url( asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ absolute_url( asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')) }}"></script>

    <script>
        $(function () {
            $('#tableAdministration').DataTable(
                {
                    stateSave: true,
                    responsive: true,
                    scrollCollapse: true,
                    paging: false,
                    scrollX: false,
                    ordering: true,
                    "order": [[2, 'asc']],
                    "columns": [
                        null,
                        null,
                        null,
                        {"orderable": false},
                        {"orderable": false},
                        {"orderable": false},
                        {"orderable": false}
                    ],
                    "language": {
                        buttons: {
                            copyTitle: 'Ajouté au presse-papiers',
                            copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',
                            copySuccess: {
                                _: '%d lignes copiées',
                                1: '1 ligne copiée'
                            }
                        },
                        "sProcessing": "Traitement en cours...",
                        "sSearch": "Rechercher&nbsp;:",
                        "sLengthMenu": "Afficher _MENU_ &eacute;l&eacute;ments",
                        "sInfo": "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                        "sInfoEmpty": "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                        "sInfoFiltered": "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                        "sInfoPostFix": "",
                        "sLoadingRecords": "Chargement en cours...",
                        "sZeroRecords": "Aucun &eacute;l&eacute;ment &agrave; afficher",
                        "sEmptyTable": "Aucune donn&eacute;e disponible dans le tableau",
                        "oPaginate": {
                            "sFirst": "Premier",
                            "sPrevious": "Pr&eacute;c&eacute;dent",
                            "sNext": "Suivant",
                            "sLast": "Dernier"
                        },
                        "oAria": {
                            "sSortAscending": ": activer pour trier la colonne par ordre croissant",
                            "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
                        },

                    }

                })

        });
    </script>
{% endblock %}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% set title='Messages' %}
{% set route_index='message_index' %}
{% set entityName='message' %}

{% block title %}{{ parent() }} {{title}}{% endblock %}

{% block stylesheets %}
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ absolute_url( asset('plugins/select2/css/select2.min.css')) }}">
    <link rel="stylesheet"
          href="{{ absolute_url( asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')) }}">
    <link rel="stylesheet" href="{{ absolute_url( asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')) }}">
{% endblock %}

{% block body_header %}
    {{ include('admin/_body_header.html.twig', {domaine: title , index : route_index}) }}
{% endblock %}

{% block sidebar_sommaire %}

{% endblock %}

{% block sidebar_button %}
    {{ include('share/__btn_save_onclick.html.twig') }}
    <span class="mb-3"></span>
    {{ include('share/__btn_return_list.html.twig',
        {   url:route_index
        }) }}
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-6  ">
            <div class="card ">
                <div class="card-body">
                    <div class="form-group row">
                        {{ form_label(form.name,'', { 'label_attr': {'class':'col-sm-3 col-form-label' }}) }}
                        <div class="col">
                            {{ form_errors(form.name) }}
                            {{ form_widget(form.name) }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="{{ form.enable.vars.id }}">
                            Afficher
                        </label>
                        <div class="col mt-1">
                            {{ form_row(form.enable) }}
                        </div>
                    </div>
                    {{ form_row(form.content) }}

                </div>
            </div>
        </div>
    </div>
    <div class="d-none">
        {{  form_rest(form) }}
        {{ include('share/__btn_save.html.twig') }}
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script src="{{ absolute_url( asset('plugins/select2/js/select2.full.min.js')) }}"></script>
    <script src="{{ absolute_url( asset('js/add_sidebar.js')) }}"></script>
{% endblock %}